export const WEBSOCKET_ORDER = 'WEBSOCKET_ORDER'
export const WEBSOCKET_ORDER_BUFFER = 'WEBSOCKET_ORDER__BUFFER'
export const WEBSOCKET_ORDER__FAILURE = 'WEBSOCKET_ORDER__FAILURE'

export const FETCH_SNAPSHOT_ORDER__SUCCESS = 'FETCH_SNAPSHOT_ORDER__SUCCESS'
export const FETCH_SNAPSHOT_ORDER__FAILURE = 'FETCH_SNAPSHOT_ORDER__FAILURE'

export const UPDATE_ORDER__SUCCESS = 'UPDATE_ORDER__SUCCESS'
export const UPDATE_ORDER__FAILURE = 'UPDATE_ORDER__FAILURE'


export const CLEAR_ORDER = 'CLEAR_ORDER'
export const CLEAR_ORDER__SUCCESS = 'CLEAR_ORDER__SUCCESS'
export const CLEAR_ORDER__FAILURE = 'CLEAR_ORDER__FAILURE'


export const CHANGE_BINANCE_ORDER = 'CHANGE_BINANCE_ORDER'
export const CHANGE_BINANCE_ORDER__LOADING = 'CHANGE_BINANCE_ORDER__LOADING'
export const CHANGE_BINANCE_ORDER__FAILURE = 'CHANGE_BINANCE_ORDER__FAILURE'